### ISSUE TITLE
Add-on doesn't work (Windows 10)

### ISSUE THREAD

**Issue by Dene33** [stuarta0/blender-photogrammetry#6]
Hello,

Tried your add-on, but it seems that something is wrong. Not sure what's the problem, because I have COLMAP installed and it works actually. I've tried 2.79b, 2.8 versions but they both doesn't work. PMVS doesn't work too. My GPU is NVIDIA NVS 4200M.

Here is the log:

> process photogrammetry
> in_blender
> out_colmap
> ERROR (bke.library): c:\b\win64_cmake_vs2017\win64_cmake_vs2017\blender.git\source\blender\blenkernel\intern\library.c:191 id_us_ensure_real: ID user count error: SCScene (from '[Main]')
> Saved: 'C:\Denis\moveai\4th_september\photogrammetry_example\renderoutput\photogrammetry\0004.jpg'
>  Time: 00:01.77 (Saving: 00:00.43)
> 
> Saved: 'C:\Denis\moveai\4th_september\photogrammetry_example\renderoutput\photogrammetry\0006.jpg'
>  Time: 00:01.60 (Saving: 00:00.29)
> 
> Saved: 'C:\Denis\moveai\4th_september\photogrammetry_example\renderoutput\photogrammetry\0008.jpg'
>  Time: 00:01.65 (Saving: 00:00.28)
> 
> Saved: 'C:\Denis\moveai\4th_september\photogrammetry_example\renderoutput\photogrammetry\0010.jpg'
>  Time: 00:01.70 (Saving: 00:00.28)
> 
> {'cameras': {}, 'resolution': (1920, 1080), 'trackers': {}}
> [ReadBundleFile] Bundle version: 0.300
> [ReadBundleFile] Reading 0 images and 0 points...
> 
> 
> @@ Conversion complete, execute "sh pmvs\/prep_pmvs.sh" to finalize
> @@ (you will first need to edit prep_pmvs.sh to specify your bundler path,
> @@  so that the script knows where to find your
> @@  RadialUndistort and Bundle2Vis binaries)
> [ReadBundleFile] Bundle version: 0.300
> [ReadBundleFile] Reading 0 images and 0 points...
> [WriteBundleFile] Writing 0 images and 0 points...
> C:\Users\Mania\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender_photogrammetry\colmap\bin\colmap.exe patch_match_stereo --workspace_path C:\Denis\moveai\4th_september\photogrammetry_example\colmap\pmvs --workspace_format PMVS --pmvs_option_name reconstruction
> Reading workspace...
> Importing PMVS workspace (option reconstruction)...
> F0820 00:25:24.831068 14032 workspace.cc:188] Check failed: range_lower < range_upper (0 vs. 0)
> *** Check failure stack trace: ***
> Traceback (most recent call last):
>   File "C:\Users\Mania\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender_photogrammetry\__init__.py", line 79, in execute
>     outputs[p.output].func(load_props, data, scene=scene)
>   File "C:\Users\Mania\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender_photogrammetry\colmap\load.py", line 48, in load
>     raise Exception('COLMAP patch_match_stereo failed, see system console for details')
> Exception: COLMAP patch_match_stereo failed, see system console for details
> 
> location: <unknown location>:-1
> 
> location: <unknown location>:-1

It would be nice if you can help. Thanks!

**Comment by stuarta0** [comment]
OK it looks like no cameras or points were generated. If this is data from the motion tracker, you'll need to solve and probably create the 3D scene first, then try processing again.

The main thing you want to see is a bunch of data in this dictionary:
```{'cameras': {}, 'resolution': (1920, 1080), 'trackers': {}}```

Which is printed in the output just after saving images.

**Comment by Dene33** [comment]
I've placed all the trackers manually. I've also tried the scene with motorcycle from your youtube video with automatic and semi-automatic solved motion trackers. Am I missing something? Thanks.

**Comment by stuarta0** [comment]
Do you mind sharing the blend file using the motorcycle video? No need to send the video itself, just the blend. I can take a look.

Use http://pasteall.org/ if you like.

**Comment by Dene33** [comment]
Here is the .blend file: https://we.tl/t-jjickZYtO9

**Comment by stuarta0** [comment]
The camera motion wasn't solved, and the 3d scene wasn't reconstructed like I mentioned. Without doing this, the structure-from-motion data isn't available.

I'll improve the error reporting so it's clearer in the addon.
