### ISSUE TITLE
saving Colmap Project file 

### ISSUE THREAD

**Issue by arielcaine** [stuarta0/blender-photogrammetry#7]
I've used the photogrammetry tool using blender motion track exporting to Colmap which worked perfectly and imported the pointcloud back into blender. however, I wish to refine the point cloud processing in colmap in order to get a better dense cloud but found that the process didnt leave a native Colmap project (.ini) file or a database (.db).
Is there a way to add a step to the process to produce these two files?
thanks

**Comment by stuarta0** [comment]
The latest code in master will create a COLMAP sparse model. This can be imported into COLMAP's GUI as described here: https://colmap.github.io/tutorial.html#importing-and-exporting

This also means COLMAP could be used on Mac and Linux if users have an external copy of COLMAP for their platform.

I've been meaning to do a release in the last few weeks but haven't had the time. If I did a release this weekend, maybe you'd like to test it?

**Comment by arielcaine** [comment]
Thanks for the reply. I will definitely be on for testing out a release whenever you get the chance to have it ready.

**Comment by stuarta0** [comment]
Try this one: https://s3-ap-southeast-2.amazonaws.com/encoded.xyz/data/github/blender-photogrammetry-1.1-windows.zip

When processing with COLMAP, you don't need to tick any of the "Import X" options. It'll create a folder hierarchy as follows:

* (your blender scene directory)
    * colmap
        * dense
            * (empty if no import options checked)
        * images
            * (all the distorted images for the sparse model)
        * sparse
            * cameras.txt
            * images.txt
            * points3D.txt

Now having looked into it, COLMAP unfortunately doesn't seem to create a database or project.ini from the sparse model, so I believe it only visualises the model (which is what you see in Blender anyway). But using the command line allows dense reconstruction regardless (see https://colmap.github.io/cli.html). If you find a way to generate a database from the sparse model, so you can then use COLMAP's GUI for dense reconstruction, let me know.

**Comment by arielcaine** [comment]
Brilliant, Thanks for this. Will test it out amd share my comments.
