### ISSUE TITLE
Blender Output Meshroom

### ISSUE THREAD

**Issue by canonex** [stuarta0/blender-photogrammetry#8]
In some cases, for some kind of surfaces, a manual tracking is required:
Is there a possibility to export blender motion tracking data to Meshroom?

Thank you,
Riccardo

**Comment by stuarta0** [comment]
Issue #4 covers the research I did in 2019 re Meshroom. I was waiting for Meshroom to create a better API for manipulating the data, hence the delay.  The wiki in the meshroom repo still says experimental, details here:
https://github.com/alicevision/meshroom/wiki/Using-known-camera-positions

**Comment by canonex** [comment]
Thank you, this could solve very specific cases!
